#!/bin/bash
znaczek=0
cyfry=0
for linia in `cat $1`
do
for znak in $linia
do
if [[ $znak =~ [a-zA-Z] ]]
then
let znaczek++
elif [[ $znak =~ [0-9] ]]
then
let cyfry++
fi
done
done
echo $znaczek
echo $cyfry

